data_path = "data/name.basics.tsv.gz"
path_to_save = "data/results/"
data_path_title_crew = "data/title.crew.tsv.gz"
data_path_title_basics = "data/title.basics.tsv.gz"
data_path_title_principals = "data/title.principals.tsv.gz"